### ISSUE TITLE
搭建不起来

### ISSUE THREAD

**Issue by GithubRobot225** [mx-space/kami#880]
你好，我把server-next 用docker-compose搭建起来了。没有问题
但是想把这个kami启动的时候发现没有avartar等各种各样的问题。

env设定: 
```
NEXT_PUBLIC_APIURL=http://127.0.0.1:2333/api/v2
NEXT_PUBLIC_GATEWAY_URL=http://127.0.0.1:2333/api/v2
NEXT_PUBLIC_TRACKING_ID=
NEXT_PUBLIC_ALWAYS_HTTPS=1

ASSETPREFIX=

```

发现avartar没有东西
```
.next\server\pages\index.js (72:22) @ IndexView

  70 | <div className="intro-avatar ">
  71 |   <img
> 72 |     src={user.avatar || avatar}
     |              ^
  73 |     alt={name}
  74 |     style={{ width: '100%' }}
  75 |   />
```

然后强行把他去掉以后，又发现

```
Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'name')

Source
.next\static\chunks\pages\_app.js (51:23) @ UserStore.get

  49 | 
  50 |   get name() {
> 51 |     return this.master.name
     |                       ^
  52 |   }
  53 |   get introduce() {
  54 |     return this.master.introduce || null
```

```
error - TypeError: Cannot read property 'seo' of undefined
    at E:\kami\.next\server\pages\_app.js:9451:37
    at processChild (E:\kami\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (E:\kami\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (E:\kami\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (E:\kami\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToString (E:\kami\node_modules\react-dom\cjs\react-dom-server.node.development.js:4298:27)
    at Object.renderPage (E:\kami\node_modules\next\dist\server\render.js:596:45)
    at Function.getInitialProps (E:\kami\.next\server\pages\_document.js:749:19)
    at Function.getInitialProps (E:\kami\.next\server\pages\_document.js:1306:85)
    at Object.loadGetInitialProps (E:\kami\node_modules\next\dist\shared\lib\utils.js:69:29)
    at renderDocument (E:\kami\node_modules\next\dist\server\render.js:609:48)
    at Object.renderToHTML (E:\kami\node_modules\next\dist\server\render.js:647:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async doRender (E:\kami\node_modules\next\dist\server\next-server.js:1144:38)
    at async E:\kami\node_modules\next\dist\server\next-server.js:1236:28 {
  page: '/'
}
error - unhandledRejection: { statusCode: 408, data: '上游服务器连接超时', message: '上游服务器连接超时' }
event - compiled successfully
error - unhandledRejection: { statusCode: 408, data: '上游服务器连接超时', message: '上游服务器连接超时' }
```

使用postman 有正常的回应
```
curl --location --request GET 'http://127.0.0.1:2333/api/v2'
```

```
{
    "name": "server-next",
    "author": "Innei <https://innei.ren>",
    "version": "3.6.18",
    "homepage": "https://github.com/mx-space/server-next#readme",
    "issues": "https://github.com/mx-space/server-next/issues",
    "hash": ""
}

```

所以也没太懂到底是错在哪。先谢谢你了

**Comment by Innei** [comment]
看下 `http://127.0.0.1:2333/api/v2/aggregate` 这个接口 有没有异常

**Comment by GithubRobot225** [comment]
接口是正常的。还是等你的docker image吧，谢谢
```
{"user":null,"seo":{"title":"我的小世界呀","description":"哈喽~欢迎光临"},"categories":[{"id":"614f2071deabbe0471336950","type":0,"name":"默认分类","slug":"default","created":"2021-09-25T13:13:21.794Z","count":0}],"page_meta":[],"lastest_note_nid":null}
```

**Comment by Innei** [comment]
先去注册用户，访问 http://127.0.0.1:2333/qaqdmin 注册

**Comment by GithubRobot225** [comment]
qaqadmin那个能进了。
但是主页还是不行: http://localhost:2323/ 就出这个错误

```
Unhandled Runtime Error

TypeError: this.master is null
Source

.next\static\chunks\pages\_app.js (51:4) @ get

  49 | 
  50 |   get name() {
> 51 |     return this.master.name
     |    ^
  52 |   }
  53 |   get introduce() {
  54 |     return this.master.introduce || null
```

**Comment by Innei** [comment]
看看这个接口 `http://127.0.0.1:2333/api/v2/master`

**Comment by GithubRobot225** [comment]
关了重开竟然好了。谢谢吗，成功搭建起来了

**Comment by Innei** [comment]
好的呀

**Comment by GithubRobot225** [comment]
似乎如果notes那一页没有数据会直接出错误，就是变成一个空的页面，连导航栏都没有了，感觉挺奇怪。

另外实在感谢你的开源，你这个项目的结构相当好，感觉能学到不少东西。我会慢慢研读的，谢谢你啦！
