### ISSUE TITLE
前端搭建求助

### ISSUE THREAD

**Issue by zsbai** [mx-space/kami#975]
后端使用docker- compose搭建，前端安装构建都没问题，pm2 start启动后报错：Internal Server Error
pnpm run dev，访问前端报错：
```
> mx-web@2.4.8 dev /opt/mx-space/kami
> cross-env NODE_ENV=development next dev -p 2323

ready - started server on 0.0.0.0:2323, url: http://localhost:2323
info  - Loaded env from /opt/mx-space/kami/.env
(node:22386) [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
(Use `node --trace-deprecation ...` to show where the warning was created)

warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
event - compiled successfully in 20.1s (2382 modules)
wait  - compiling /...
event - compiled successfully in 10.7s (2630 modules)
wait  - compiling /_error...
event - compiled successfully in 320 ms (2630 modules)
warn  - You have added a custom /_error page without a custom /404 page. This prevents the 404 page from being auto statically optimized.
See here for info: https://nextjs.org/docs/messages/custom-error-no-custom-404
Error: [object Object]
    at DevServer.renderErrorToResponse (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.4_dfacd8ba41540a3950547fefe259848d/node_modules/next/dist/server/next-server.js:1724:86)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DevServer.renderToResponse (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.4_dfacd8ba41540a3950547fefe259848d/node_modules/next/dist/server/next-server.js:1641:30)
    at async DevServer.pipe (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.4_dfacd8ba41540a3950547fefe259848d/node_modules/next/dist/server/next-server.js:1148:25)
    at async Object.fn (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.4_dfacd8ba41540a3950547fefe259848d/node_modules/next/dist/server/next-server.js:949:21)
    at async Router.execute (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.4_dfacd8ba41540a3950547fefe259848d/node_modules/next/dist/server/router.js:222:32)
    at async DevServer.run (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.4_dfacd8ba41540a3950547fefe259848d/node_modules/next/dist/server/next-server.js:1125:29)
    at async DevServer.run (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.4_dfacd8ba41540a3950547fefe259848d/node_modules/next/dist/server/dev/next-dev-server.js:439:20)
    at async DevServer.handleRequest (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.4_dfacd8ba41540a3950547fefe259848d/node_modules/next/dist/server/next-server.js:320:20)
error - Error: [object Object]
Error: [object Object]
    at DevServer.renderErrorToResponse (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.4_dfacd8ba41540a3950547fefe259848d/node_modules/next/dist/server/next-server.js:1724:86)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async pipe.req.req (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.4_dfacd8ba41540a3950547fefe259848d/node_modules/next/dist/server/next-server.js:1670:30)
    at async DevServer.pipe (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.4_dfacd8ba41540a3950547fefe259848d/node_modules/next/dist/server/next-server.js:1148:25)
    at async DevServer.run (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.4_dfacd8ba41540a3950547fefe259848d/node_modules/next/dist/server/dev/next-dev-server.js:446:24)
    at async DevServer.handleRequest (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.4_dfacd8ba41540a3950547fefe259848d/node_modules/next/dist/server/next-server.js:320:20)

```
.env文件内容如下：
```
NEXT_PUBLIC_APIURL=http://127.0.0.1:2333
NEXT_PUBLIC_GATEWAY_URL=http://127.0.0.1:2333
NEXT_PUBLIC_TRACKING_ID=
NEXT_PUBLIC_ALWAYS_HTTPS=0

ASSETPREFIX=
```
不太明白是哪里出问题了，由于不太了解nodejs，请教一个问题：请问前端可以为静态文件搭建在例如GitHub pages的静态托管上嘛？

**Comment by zsbai** [comment]
突然发现文档注明不能使用淘宝源...?pnpm我默认用的好像就是淘宝源...换源重新测试下

**Comment by Innei** [comment]
环境变量有没有填 .env

**Comment by zsbai** [comment]
> 环境变量有没有填 .env

请问是在哪里检查呢...不好意思实在是对nodejs不熟悉

**Comment by Innei** [comment]
.env.example 复制一份改名.env

**Comment by zsbai** [comment]
啊这个已经复制了的，.env里的内容是默认的没有改

**Comment by wibus-wee** [comment]
> 啊这个已经复制了的，.env里的内容是默认的没有改 前端直接访问出现Internal Server Error是正常的吗？

截取命令`pm2 log`里面的报错出来看看

**Comment by zsbai** [comment]
```
/root/.pm2/logs/mx-kami-out-3.log last 15 lines:
3|mx-kami  | info  - Loaded env from /opt/mx-space/kami/.env
3|mx-kami  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
3|mx-kami  | $ /opt/mx-space/kami/node_modules/.bin/next start -p 2323
3|mx-kami  | ready - started server on 0.0.0.0:2323, url: http://localhost:2323
3|mx-kami  | info  - Loaded env from /opt/mx-space/kami/.env
3|mx-kami  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
3|mx-kami  | $ /opt/mx-space/kami/node_modules/.bin/next start -p 2323
3|mx-kami  | ready - started server on 0.0.0.0:2323, url: http://localhost:2323
3|mx-kami  | info  - Loaded env from /opt/mx-space/kami/.env
3|mx-kami  | $ /opt/mx-space/kami/node_modules/.bin/next start -p 2323
3|mx-kami  | ready - started server on 0.0.0.0:2323, url: http://localhost:2323
3|mx-kami  | info  - Loaded env from /opt/mx-space/kami/.env
3|mx-kami  | $ /opt/mx-space/kami/node_modules/.bin/next start -p 2323
3|mx-kami  | ready - started server on 0.0.0.0:2323, url: http://localhost:2323
3|mx-kami  | info  - Loaded env from /opt/mx-space/kami/.env

/root/.pm2/logs/mx-kami-error-3.log last 15 lines:
3|mx-kami  |     at async Server.pipe (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.7_26cee3e4b82436ed28df882481d4fc62/node_modules/next/dist/server/next-server.js:1158:25)
3|mx-kami  |     at async Object.fn (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.7_26cee3e4b82436ed28df882481d4fc62/node_modules/next/dist/server/next-server.js:959:21)
3|mx-kami  |     at async Router.execute (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.7_26cee3e4b82436ed28df882481d4fc62/node_modules/next/dist/server/router.js:222:32)
3|mx-kami  |     at async Server.run (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.7_26cee3e4b82436ed28df882481d4fc62/node_modules/next/dist/server/next-server.js:1135:29)
3|mx-kami  |     at async Server.handleRequest (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.7_26cee3e4b82436ed28df882481d4fc62/node_modules/next/dist/server/next-server.js:325:20)
3|mx-kami  | Error: [object Object]
3|mx-kami  |     at Server.renderToResponse (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.7_26cee3e4b82436ed28df882481d4fc62/node_modules/next/dist/server/next-server.js:1641:72)
3|mx-kami  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
3|mx-kami  |     at async Server.pipe (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.7_26cee3e4b82436ed28df882481d4fc62/node_modules/next/dist/server/next-server.js:1158:25)
3|mx-kami  |     at async Object.fn (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.7_26cee3e4b82436ed28df882481d4fc62/node_modules/next/dist/server/next-server.js:959:21)
3|mx-kami  |     at async Router.execute (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.7_26cee3e4b82436ed28df882481d4fc62/node_modules/next/dist/server/router.js:222:32)
3|mx-kami  |     at async Server.run (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.7_26cee3e4b82436ed28df882481d4fc62/node_modules/next/dist/server/next-server.js:1135:29)
3|mx-kami  |     at async Server.handleRequest (/opt/mx-space/kami/node_modules/.pnpm/next@12.0.7_26cee3e4b82436ed28df882481d4fc62/node_modules/next/dist/server/next-server.js:325:20)
3|mx-kami  | (node:14662) [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
3|mx-kami  | (Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by Innei** [comment]
前端的wnv怎么写的 十成是接口地址没配好

**Comment by zsbai** [comment]
> 前端的env怎么写的 十成是接口地址没配好

.......确实是因为接口地址，我当时是直接复制.env.example到.env的，一点东西都没改，刚发现.env.example中api没有写/api/v2

**Comment by zsbai** [comment]
> 
<img width="582" alt="截屏2021-12-13 下午11 18 17" src="https://user-images.githubusercontent.com/62942942/145838433-9ea8a885-e207-44df-8d0e-43893364cef0.png">
你好，请问下频繁出现这个是怎么回事呢，docker日志和pm2 log也没发现出现异常,f12也没看到请求异常的信息，但有时候刷新又突然可以加载出来emmm

**Comment by zsbai** [comment]
> <img alt="截屏2021-12-13 下午11 18 17" width="582" src="https://user-images.githubusercontent.com/62942942/145838433-9ea8a885-e207-44df-8d0e-43893364cef0.png">
> 
> 你好，请问下频繁出现这个是怎么回事呢，docker日志和pm2 log也没发现出现异常,f12也没看到请求异常的信息，但有时候刷新又突然可以加载出来emmm

访问http://服务端/api/v2/aggregate是正常返回的，有时候f12可以看到访问这个请求返回空，但我自己手动访问有没有问题
